[build]
  command = "npm install"
  functions = "netlify/functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/webhooks/*"
  to = "/.netlify/functions/webhook/*"
  status = 200

[[redirects]]
  from = "/auth/*"
  to = "/.netlify/functions/auth-quickbooks/*"
  status = 200

[context.production.environment]
  NODE_ENV = "production"

[context.development.environment]
  NODE_ENV = "development"