[build]
  command = "npm install"
  functions = "netlify/functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/webhooks/*"
  to = "/.netlify/functions/webhook/*"
  status = 200

[[redirects]]
  from = "/auth/quickbooks"
  to = "/.netlify/functions/auth-quickbooks"
  status = 200

[[redirects]]
  from = "/callback/quickbooks"
  to = "/.netlify/functions/auth-quickbooks/callback"
  status = 200

[context.production.environment]
  NODE_ENV = "production"

[context.development.environment]
  NODE_ENV = "development"

# Scheduled function for monthly ad spend update
# This runs on the 3rd of every month at 2 AM UTC
[functions."update-ad-spend"]
  schedule = "0 2 3 * *"

# Manual trigger endpoint for ad spend update
[[redirects]]
  from = "/api/update-ad-spend"
  to = "/.netlify/functions/update-ad-spend"
  status = 200

# QuickBooks OAuth endpoints
[[redirects]]
  from = "/qbo-auth"
  to = "/.netlify/functions/qbo-auth"
  status = 200

[[redirects]]
  from = "/qbo-auth/callback"
  to = "/.netlify/functions/qbo-auth"
  status = 200